### ISSUE TITLE
libssl1.1 (missing) when following the README instructions

### ISSUE THREAD

**Issue by djc** [Surnet/docker-wkhtmltopdf#10]
When following the README instructions to build a JDK-base image that includes wkhtmltopdf. However, when doing so, I get an error from `apk`:

```
ERROR: unsatisfiable constraints:
  libssl1.1 (missing):
    required by: world[libssl1.1]
```

**Comment by chdanielmueller** [comment]
What alpine version is the JDK-base image based on?

**Comment by djc** [comment]
Thanks for the quick response! It was based on openjdk:8u151-jre-alpine which I guess is quite old. When I use 8u212-jre-alpine instead, it seems to work.

**Comment by chdanielmueller** [comment]
alpine 3.8 and older used libssl1.0.
I quickly checked and saw 8u212-jre-alpine is based on alpine 3.9.

If you would need to use the older image you could check the alpine version it is based on and then use an appropriate image version to copy wkhtmltopdf from.
Also you could copy the dependencies for the version from the Dockerfile archive
https://github.com/Surnet/docker-wkhtmltopdf/tree/master/archive/alpine-wkhtmltopdf

**Comment by djc** [comment]
Thanks!
