### ISSUE TITLE
wkhtmltopdf 0.12.5

### ISSUE THREAD

**Issue by WojtekKruszewski** [Surnet/docker-wkhtmltopdf#2]
wkhtmltopdf version 0.12.5 has been released – could you add it to this project?

**Comment by chdanielmueller** [comment]
Sure, I will take a look at it this weekend.
If everything goes as planned the new images should be up by next week.

**Comment by chdanielmueller** [comment]
Hi there,

Sorry I missed to follow up.
I was unable to perform a successful build.
I think it is an issue with the patches.

Thanks,
Daniel

**Comment by chdanielmueller** [comment]
The new versions are currently uploading to docker hub
