### ISSUE TITLE
How to install wkhtmltopdf on Debian base image

### ISSUE THREAD

**Issue by Liu-Chunhui** [Surnet/docker-wkhtmltopdf#20]
We would like to use Debian instead of the Alpine as the image. 

Could you please help us to list all the dependencies we have to install to run wkhtmltopdf? 

Thank you very much

**Comment by chdanielmueller** [comment]
Hi @Liu-Chunhui 

This repo is specifically for alpine images. Please visit https://github.com/wkhtmltopdf/packaging for more information. Or open an Issue there if you have any problems with creating your build.

Thanks,
Daniel

**Comment by chdanielmueller** [comment]
There is a precompiled binary for wkhtmltopdf for Debian:
https://wkhtmltopdf.org/downloads.html
