### ISSUE TITLE
New features of JS

### ISSUE THREAD

**Issue by madatbay** [Surnet/docker-wkhtmltopdf#25]
Most of the js features are not working, so I have to depreciate newer features to older ones. Cannot use foreach, const, .then, async/await, .includes, and etc. If I use it, the script file is ignored on pdf generation. And cannot use another feature for some of then like .then

**Comment by chdanielmueller** [comment]
Hi @madatbay 

This sounds like you want to use those features while generating a pdf via wkhtmltopdf? e.g. a script within the html?
This would be an issue for https://github.com/wkhtmltopdf/wkhtmltopdf

If I got you wrong then the issue has probably to do with the node version in the image you are using.
If that's the case please try with `16.13.1-0.12.6-small` or `16.13.1-0.12.6-full` which feature all capabilities of node@16

**Comment by chdanielmueller** [comment]
Thank you for getting back to the issue and closing it! 👍

Depending on your use case taking a look at https://babeljs.io could be worth it.
