### ISSUE TITLE
Release update for alpine:3.16

### ISSUE THREAD

**Issue by jtormey** [Surnet/docker-wkhtmltopdf#26]
Hi! I've been running this flawlessly on version 3.15, however I'm now attempting to update my builder image to 3.16 (as a result of updating other dependencies) and doing so introduces errors on container start. From my tests and searching around, this is due to differences in alpine versions.

Would it be possible to release an update in order to support alpine 3.16? Thank you!

Relevant SO post with the exact error + suggested resolution: https://stackoverflow.com/questions/72609505/issue-with-building-elixir-and-beam-on-alpine-linux

**Comment by chdanielmueller** [comment]
I'm trying to run a build right now.
Will keep you updated

**Comment by chdanielmueller** [comment]
3.16.0-0.12.6-small and 3.16.0-0.12.6-full are now uploaded.
If you are happy with the images please close the issue afterwards.

**Comment by jtormey** [comment]
Works beautifully! Thank you!
