### ISSUE TITLE
Some CSS features are not working

### ISSUE THREAD

**Issue by jvitoroc17** [Surnet/docker-wkhtmltopdf#27]
CSS features like flex and trasnform are not working, they only work if I put the "-webkit-" prefix. Maybe we need to update the Qt?

**Comment by chdanielmueller** [comment]
This is an ongoing issue in wkhtmltopdf.
e.g. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1522#issuecomment-1073300030

This docker image only does the build for alpine linux.
