### ISSUE TITLE
alpine support  wkhtmltopdf-dev

### ISSUE THREAD

**Issue by jilieryuyi** [Surnet/docker-wkhtmltopdf#37]
not found c header files in the docker image

**Comment by chdanielmueller** [comment]
Please try a `full` version e.g. [3.18.0-0.12.6-full](https://github.com/orgs/Surnet/packages/container/alpine-wkhtmltopdf/107015217?tag=3.18.0-0.12.6-full)

It should contain what you are looking for at `/bin/libwkhtmltox*`
