### ISSUE TITLE
Alpine 3.19

### ISSUE THREAD

**Issue by klausmeyer** [Surnet/docker-wkhtmltopdf#41]
Hi,

I tried to use your repository to build a `wkhtmltopdf` binary for alpine 3.19 (released on 2023-12-07) and had to make some changes to get it working with the now dropped `libssl1.1` package which was replaced with a `libssl3` one:

https://github.com/Surnet/docker-wkhtmltopdf/compare/master...klausmeyer:docker-wkhtmltopdf:feat/alpine-3.19

Should I create a PR or would you like to address it on your own / in a different way?

Best, Klaus

**Comment by jwjenkin** [comment]
Bump on this. Would really like to get this sucker in

**Comment by PAXANDDOS** [comment]
I'll bump this as well, really waiting

**Comment by chdanielmueller** [comment]
Build is running and will be published soon
