### ISSUE TITLE
Document the use of libssl3 for other images based on alpine3.19 in readme

### ISSUE THREAD

**Issue by Zuruuh** [Surnet/docker-wkhtmltopdf#45]
hey there, first, thanks for the docker image, it helped me a lot to build some great stuff :heart: 😄 

since #43 the build uses libssl3 on alpine3.19 since libssl1.1 isn't available anymore. There should probably be a note about that in the readme to tell users of alpine versions above 3.19 to use libssl3 no (talking about the `Other images` section) ?

**Comment by chdanielmueller** [comment]
Absolutely.
I edited the README.md accordingly.

And thanks for the Sponsorship. ❤️
I appreciate it!
