### ISSUE TITLE
Alpine 3.20

### ISSUE THREAD

**Issue by keeguon** [Surnet/docker-wkhtmltopdf#50]
Hey @chdanielmueller, Alpine 3.20 was released last week any plans to release new versions ?

P.S. can do a pull request with those over the weekend if I can help in any ways.

**Comment by chdanielmueller** [comment]
Hey @keeguon 

Thank you for bringing this to my attention.

I am trying to build the images for `alpine:3.20.0`, `node:20.14.0-alpine3.20` and `python:3.12.3-alpine3.20` right now.
Let's see if there are any changes needed for the build to succeed.
Otherwise the images should be up soon.
