### ISSUE TITLE
How can I use this inside my dockerfile

### ISSUE THREAD

**Issue by laur1s** [Surnet/docker-wkhtmltopdf#8]
Hi, 

I'm building a PHP app and I want to use wkhtmltopdf on alpine. Could, I just copy   	Dockerfile_3.9-0.12.5-small to my dockerfile or are there better alternatives. Thanks

**Comment by chdanielmueller** [comment]
Hi @laur1s, 

Please check the Readme.md -> Other Images
https://github.com/Surnet/docker-wkhtmltopdf#other-images
This should explain how to use it together with a alpine based php image.

Cheers,
Daniel
